### ISSUE TITLE
Tests are failing in CI for new branches

### ISSUE THREAD

**Issue by pkanal** [honeycombio/opentelemetry-collector-configs#52]
**Versions**
1.6.0 (latest)

**Steps to reproduce**
1. Create a branch with some changes
2. Open PR
3. Tests will fail with error message:

`module go.opentelemetry.io/collector@latest found (v0.68.0), but does not contain package go.opentelemetry.io/collector/service/servicetest\n`

Failing step in CircleCI: https://app.circleci.com/pipelines/github/honeycombio/opentelemetry-collector-configs/229/workflows/13b5481b-e2db-4537-a51e-9a8578cef1a6/jobs/211

**Additional context**
This might be happening because the OCB has an explicit tag (0.66.0) and the collector contrib is pulling the most recent git tag so they can get out of sync.

**Comment by TylerHelmuth** [comment]
I am able to get `make test` to fail locally so I think this is a Go package issue instead of a CI issue.  My best guess at the moment is that something is funky with some import statements in the 0.66.0 version of some of our dependencies.  I am going to bump to 0.67.0, which still isn't latest, and see what happens.

**Comment by TylerHelmuth** [comment]
0.67.0 worked as expected so I think the issue is only with 0.66.0.  I'll get CI working again by bumping up the version.
